### ISSUE TITLE
Support local pcap analysis for remote zqd import

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/brim#1296]
We don't currently plan to support ingesting pcap's on cloud services instances of zqd. However, we could use Brim & its local zqd to generate ZNG records from a pcap, then copy the records to a remote zqd instance. That would come close to achieving the same result, without needing to upload large pcaps & operate Zeek/Suricata in the cloud. 

A downside to just copying the ZNG is that the 'Wireshark' button wouldn't work the same compared to just using a local space. We could eventually support Wireshark by associating the local pcap path with the remote space in some fashion, but that's not needed for this initial support.

**Comment by philrz** [comment]
This is now possible using the steps described in the [Remote Lakes](https://github.com/brimdata/brim/wiki/Remote-Lakes) article.

Closing this issue.
