### ISSUE TITLE
Server notifications to Brim

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/brim#1471]
When changes occur to backend resources in a tenant account, like space creation/deletion, Brim should reflect the change quickly & without requiring the user to manually refresh their view. 

To implement this, we could add an API route to zqd that pushes notifications back to Brim or other zqd clients, similar to how we send status messages during ingest. In zqd, we've already added a 'notifier' entity that is used to trigger actions in Temporal (for example, when data is written to a space, we ensure that compaction is triggered sometime afterward). We could re-use that mechanism to get notifications to Brim. In our clustered zqd, we could use Redis pub/sub to broadcast & receive notifications.

**Comment by philrz** [comment]
Note-to-self: When we implement this, I can improve the "Remote `zqd`" article in the wiki. Right now I'm calling out the caveat that users need to select **Reload** from the drop-down menu after posting new data via `zapi`, for instance.

**Comment by alfred-landrum** [comment]
Related: https://github.com/brimsec/brim/issues/950

**Comment by philrz** [comment]
The original requirement expressed in the opening text of this issue does indeed seem to have been addressed by [#2791](https://github.com/brimdata/zed/pull/2791) and https://github.com/brimdata/brim/pull/1702, i.e., pool creation/deletion is now reflected without requiring the user to refresh their view (#950). Per the comment above, the Remote Lakes article was updated some time back to remove the pointer about requiring manual refresh.

Closing this one as a duplicate.
