### ISSUE TITLE
Brim CI failure: "TypeError: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1529]
[https://github.com/brimsec/brim/actions/runs/677403237](https://github.com/brimsec/brim/actions/runs/677403237) was a run of the Brim CI that was triggered by the advance of the `zq` pointer. The run was at Brim commit 31bbcd0 attempting to run with `zq` commit brimsec/zq@50bd002 (associated with brimsec/zq#2386). The failure was in the "histogram deep inspection" test in `itest/tests/ingest.test.ts` and the failure was attached in this screenshot:

![image](https://user-images.githubusercontent.com/5934157/112200542-92f43800-8bcc-11eb-829b-2613ed3c4349.png)

I've since performed a local run of the Brim CI using that combination of commits and was not able to reproduce the failure. A subsequent `zq` commit triggered a re-run of the CI and it passed, so the `zq` pointer has since been successfully advanced. This seems to indicate that the problem might be intermittent.

**Comment by jameskerr** [comment]
I was able to reproduce this by navigating to a workspace that did not exists. In the PR that fixes this, I'll add a global function called `navTo(url)`. I'll add an integration test that does this too.
