### ISSUE TITLE
Security Specific Right Clicks

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1542]
Only show the Virus Total and Whois right click options if the security module is installed (brimcap is present).

If possible, refactor the current right click options to be available to plugin authors. It would also be good to remove unnecessary duplication if there is any.

**Comment by philrz** [comment]
While I _do_ think the current hard-wiring needs to change (i.e. activation of the VirusTotal option should _not_ be dependent on the hard-wired list of named Zeek fields it is today) I sense we might be pushing too far if we _only_ activate these when Brimcap is present. Non-pcap users will still have the ability to import data directly to the app that might contain IPs they'd want to be able to look up in Whois, or hashes/domains that they'd like to be able to look up in VirusTotal.

**Comment by philrz** [comment]
We discussed this one as a group and reached consensus that for now we'll keep these options always available via right-click regardless of whether Brimcap is installed.
