### ISSUE TITLE
Conditional Preferences

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1545]
Only show Zeek and suricata options in the preferences if the security module is installed (brimcap is present). @mattnibs can show us if/how we can use these options in the brimcap invocation. He can also tell us if some the options are no longer needed in which case remove them from the preferences.

**Comment by philrz** [comment]
It does seem like we should be able to remove these entirely and rely on the config living within Brimcap itself. Perhaps in some fancy vision of the future, modules might be able to register with the app and effectively communicate "here's some user-configurable options for this module that could be made change-able via the app Preferences" along with some API for moving those changes back & forth. But that feels a long ways off.

**Comment by philrz** [comment]
We discussed this one as a group. Brimcap's interactions with the Brim app are still being implemented, but the way things are headed, it seems that things like alternate Zeek/Suricata are likely to be configured via YAML on the Brimcap side. We talked about maybe giving options in the Brim Preferences that let the user point at different Brimcap YAML configs and/or edit the Brimcap YAML config that's currently in use. Let's hold this issue open to at least make sure we find a clean way to replace the Zeek/Suricata options that are there now with whatever seems reasonable for our first release that leverages Brimcap.

**Comment by philrz** [comment]
@mattnibs, @nwt, @mason-fish and I had a discussion where we broke this topic out into a handful of separate issues:

*   #1593
*   #1594
*   #1595
*   brimdata/brimcap#64

Those are now all marked as "blocking" this one, since they add up to a functional replacement of what the user had from these Preferences in the past.
