### ISSUE TITLE
Update "ZQL Syntax Docs" pull-down menu option

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1546]
Rename "ZQL" to "Zed" in the App Menu => help submenu.

**Comment by philrz** [comment]
Verified in Brim commit 9a3eeae.

As shown in the attached video, now the pull-down menu says "Zed Syntax Docs" and still brings up the correct URL in the browser.

https://user-images.githubusercontent.com/5934157/117889038-c025a400-b267-11eb-8134-05c7f6ef38fb.mp4

Thanks @jameskerr!
