### ISSUE TITLE
Brimcap-plugin: "pcap_support" replacement

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#1616]
Issue: We no longer have the `space.pcap_support` data that was previously stored by zqd to indicate whether a pool contains data imported from a pcap file (and therefore has an underlying pcap for it's ingested data). We had been using this to disable the wireshark button for conn records imported directly from zeek logs. However, since the brimcap changes, it now remains enabled for those zeek logs.

Solution: For now, we will continue with this new, not-ideal behavior and notify users if there are no underlying packets *after* they click on the button.

Later on there might be more we can do, such as spawning `brimcap search` every time a log is selected (highlighted in the search results/viewer) to check if pcaps are supported, and then enable/disable the button accordingly. As it stands now, running that search automatically on each log selection change could become expensive, especially if the user quickly highlights several records in succession which each may result in a hefty brimcap operation that gets spawned solely for the purpose of checking if we should enable the wireshark button or not. If we can tweak the search command to offer an inexpensive "peak" mechanism used to check for pcap support then this could be a better solution.

**Comment by philrz** [comment]
Verified with nightly build https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-1fc5d6d2.0/macos/Brim-0.25.0-prerelease-1fc5d6d2.0.dmg (so, Brim commit 1fc5d6d).

In the attached video, I've imported the [Zeek zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-default) (so, pre-existing Zeek logs... not ones generated from a pcap). When I click the active **Packets** button, the app helpfully informs me that there's no packets found.

https://user-images.githubusercontent.com/5934157/117715680-79637b80-b18d-11eb-9352-44f527ec5983.mp4

As @mason-fish indicates in the original issue description, this follows from how things have changed in the Brimcap & Zed Lake era. Previously, there was a 1-to-1 mapping between pcaps and Spaces in Brim, such that if a pcap was imported, the Space consisted entirely of Zeek+Suricata logs made from that pcap, and in this regard any Zeek `conn` record in such a Space could be assumed to have the 5-tuple+time information necessary to extract the flow from the original pcap. However, in the Zed Lake era it's possible to use `brimcap load` to import multiple pcaps and have their logs incrementally appear in the same pool, add non-pcap-based logs to a pool that may already contain pcap-based logs, start a pool out with pcap-based logs and then delete the pcap-based logs, etc. Therefore, the binary "yes/no" we had in the past indicating "pcap support" no longer makes sense. For now we're sticking with the behavior shown here. As @mason-fish mentioned, in the future we might look into lightweight ways we could "peek" in the packet index to see if a flow is there before we activate the **Packets**. If users express any confusion about this in the interim, we could also add a wiki article and link to it from the error message.

Thanks @mason-fish!
