### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1634]
Repro is with Brim 9a3eeae.

While attempting the verification of the Space migrations as described in [https://github.com/brimdata/brim/issues/1567#issuecomment-839370636,](https://github.com/brimdata/brim/issues/1567#issuecomment-839370636,) I had DevTools open and was looking for signs of errors. I observed these warnings that @jameskerr confirmed to _not_ be indicative of the failure with the migrations ("It’s mad that I put a \<div> inside a \<span>"), but he did say they're worth addressing so we keep the Console from getting cluttered with lots of red herrings.

![](https://user-images.githubusercontent.com/5934157/117906407-b14fe900-b289-11eb-8736-b8e5f7e50b27.png)

**Comment by jameskerr** [comment]
This got fixed with #1636

**Comment by philrz** [comment]
Verified in Brim commit 43b0ed5 via nightly macOS build \[https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg.](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg).

As shown in the attached video, now during the Space migration, DevTools only shows the relevant informative messages regarding the start/completion of each migration.

https://user-images.githubusercontent.com/5934157/118417117-8558ad00-b667-11eb-8a3c-2fb2054718fa.mp4

Thanks @jameskerr!
