### ISSUE TITLE
"non-serializable value" error on console when loading Pool info

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1688]
Repro is with Brim commit 440d3a9 which uses Zed commit `fd273d1`.

When loading Pool info (such as after dragging new data into Brim or selecting **View > Reload** from the pull-down menu) I've noticed messages on the console that look like:

```
A non-serializable value was detected in an action, in the path: `pool.span.ts`. Value: 1617490638655036000n 
Take a look at the logic that dispatched this action:  {
  type: '$POOLS_DETAIL',
  workspaceId: 'localhost:9867',
  pool: {
    id: '0x0d3ef7f275ff4f0414f388cf3c1b5ece565d3020',
    size: 2498,
    span: { ts: 1617490638655036000n, dur: 311124001n }
  }
} 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants) 
```

When reviewing this with @jameskerr, he remarked:

> This is a bug. It turns out that you can’t JSON.stringify a bigint. We stringify the redux state when we persist it. We’ll need to change that to an {sec, ns} object.
> 
> ```
> > data
> { num: 100n }
> > JSON.stringify(data)
> Uncaught TypeError: Do not know how to serialize a BigInt
>    at JSON.stringify (<anonymous>)
> ```

**Comment by jameskerr** [comment]
After more investigation, this is more of a warning than a bug. I just looked at the code and nothing seems like it will break. This is just redux warning us that we sent a non-serializable "action". However, when it gets to the store, it is serializable. The thing that we need serialize is the store, not the actions. However, it'd be nice to fix this and silence the warning.

**Comment by philrz** [comment]
I've verified in Brim commit a857ff9 that now when I select **View > Reload** when a populated Pool is present, the console where my `npm start` is running is silent rather than printing the error as it did before.

Thanks @mason-fish!
