### ISSUE TITLE
Activating Brim on Mac with no existing windows does nothing

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1770]
This issue was reported by a user in a [thread on public Slack](https://brimsec.slack.com/archives/C024JHN96SC/p1628609137008200).

It's expected that a new search window would be opened if there are no open brim windows. This is how most mac apps work.

This code will be handled in the on "activate" event in the main process.

I imagine this is related to the new hidden window.

**Comment by willie-lin** [comment]
MacOS BigSur 11.5 Have the same problem

**Comment by philrz** [comment]
Verified with beta build https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-f42a36b7.0/macos/Brim-0.25.0-prerelease-f42a36b7.0.dmg.

As shown in the attached video, now if all Brim windows are closed but the app remains alive (as evidenced by the small black dot under the icon in the dock), and the Brim icon in the dock is once again clicked, a new window is now opened.

https://user-images.githubusercontent.com/5934157/130161518-7e75cc58-d70d-4664-926a-682b619b992b.mp4

Thanks @mason-fish!
