### ISSUE TITLE
where download brim 0.25

### ISSUE THREAD

**Issue by nmweizi** [brimdata/brim#1771]
where download brim 0.25

**Comment by philrz** [comment]
Hi @nmweizi. Thanks for your interest in Brim. I assume your question is motivated by the presence of the docs in the Brim wiki that mention release `v0.25.0` as if it's already out. Indeed, those docs are forward-looking to prepare for that next GA release, but it's still in beta at the moment. If you want to get involved with the beta testing, the best thing to do is join the Brim public community Slack via the self-invite link at [https://www.brimsecurity.com/join-slack/](https://www.brimsecurity.com/join-slack/) and join the `#beta` channel there. We periodically post links to the latest beta build refreshes and are able to field questions there from users who hit issues. So feel free to join up over there if you'd like, or if you're not interested in beta testing, you'll eventually see the GA `v0.25.0` posted on the Brim GitHub Releases page at [https://github.com/brimdata/brim/releases](https://github.com/brimdata/brim/releases) and linked from the Downloads page at the web site at [https://www.brimsecurity.com/download/,](https://www.brimsecurity.com/download/,) hopefully within a couple weeks.

Hope that helps. I'll look for you at the `#beta` channel, and will close this issue for now.
