### ISSUE TITLE
Tabs & Session History disappear after closing the last Brim window

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1817]
Repro is with Brim commit af1f358 via macOS beta artifact https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-af1f3581.0/macos/Brim-0.25.0-prerelease-af1f3581.0.dmg. This issue was originally reported by a community user.

While the **File > New Window** option exists in Brim, it seems like many users may only ever open Brim by clicking the icon in their OS and then close/quit from that one Brim window when they're done. In this regard, the subtle differences between "quitting the app" and "closing the last window" might elude these users.

The setup for both of the following two videos is the same. I've imported [ifconfig.pcapng.gz](https://github.com/brimdata/brim/files/7131110/ifconfig.pcapng.gz) (after uncompressing) and opened the same pool in multiple tabs, executing Zed query `curl` in one tab and `count() by _path` in the other.

As shown in the attached video, If I then select **File > Quit** to to close the app, then when I re-open the app, all my tabs are right where I left them.

https://user-images.githubusercontent.com/5934157/132566032-82aeb153-3323-467d-a143-a0df089e5897.mp4

OTOH, if I click the "red dot" on macOS, when I click the icon in the dock to "re-open Brim", my tabs are gone.

https://user-images.githubusercontent.com/5934157/132566111-3b93a0da-69f5-45a8-8d92-088a056fd0a5.mp4

Now, as a Brim insider, I understand what's going on here: The first video shows "quitting the app" and maintaining all my state (which might have involved multiple windows and all their tabs, if I had more open), while the second is "closing the last window" and clearing all state related to it (effectively bringing me back to a clean slate). As a user, if I'd had multiple windows open with different tabs on each, the idea of clicking the "red dot" to close _one_  window and having its tabs disappear is probably not shocking. OTOH, if I only ever use Brim with a single window, the subtle difference between "quit" and "close" (and the tiny black dot under the Brim icon in my dock) might be lost on me. Indeed, the community user who reported this bug effectively fell into that trap and thought they were seeing a bug. Once I explained all of the above, they now understood what was going on and may change their workflow to be more careful about using "quit". However, the fact they had to hear a lengthy explanation to be convinced it's not a bug implies we could do better.

My first thought is that maybe if the user is closing the _last_ window, we could pop up some kind of warning along the lines of:

> You're closing the last window in Brim, which will close your <N> tabs. Are you sure you want to do this?
> (Select File > Quit to close the application while maintaining all window/tab settings)

If we wanted to get fancy, we could also:

1. Not pop this up if the only tabs that are open are "blank" (no pool selected and no query entered)
2. Have one of those "Don't show me this warning again" checkboxes

Personally I'm not advocating doing fancy things, but figured I'd write them down for completeness.

Also, the community user said they observed a similar effect on Windows, so when we decide to pursue this topic, let's make sure the fix works on all supported platforms.

**Comment by jameskerr** [comment]
What we should do to fix this is simply "hide" the last window if the user closes it on mac. Then when they activate it again, everything will be exactly as they left it. 

Let's also do the same thing if they click "new window".

**Comment by philrz** [comment]
This one has been open long enough that unfortunately another community user has likely bumped into a new variation on the issue. In brief, the same symptom described above of losing tabs when closing the  app window is now also observed for the recently-added new Session History entries.

To see it in action, compare these two videos taken with Zui Insiders [0.30.1-86](https://github.com/brimdata/zui-insiders/releases/tag/v0.30.1-86). In the first, we see that when we "Quit" the app, the queries that accumulated in our History are still present when we relaunch the app.

https://user-images.githubusercontent.com/5934157/193948099-955f288a-eacf-4372-936b-17db8141c682.mp4

In the second we see that "Closing" the window causes the loss of the accumulated History queries.

https://user-images.githubusercontent.com/5934157/193948082-38adbdf9-ff2d-417b-bf66-5cf348ff4dbc.mp4

Note that I've reproduced this symptom on _all_ supported platforms: Mac, Windows, Linux. The Mac example shown here is subtly different from Linux and Windows since when closing the last app window on Mac the "dot" remains under the app icon in the dock, which is an indication that the app itself is still running (and, indeed, the `zed serve` process is still alive as well), so it needs to be explicitly Quit before it can be relaunched. OTOH on both Windows and Linux, closing the last app window results in the complete exit of the app, so I think it's understandable that a user would be surprised by the difference in how their state is saved (or not) between the variations on exit.

The community zync user that most recently reported the issue was using Windows. During a session in which we were hearing overall app feedback, they recounted a general sense among their team that sometimes History queries would go missing when closing and re-opening the app, but they'd not narrowed down a specific set of repro steps. Therefore I cannot say with 100% certainty that what I've shown here is the root cause for their lost History entires as well, but it certainly could be. That same user also indicated that their team doesn't tend to rely on the app's saved state and instead store Zed queries in other tools and cut & paste them into the app. So fixing issues like this one might go a long way toward starting to rebuild their faith in saved state in the app.

**Comment by philrz** [comment]
Verified in Zui Insiders `0.30.1-184` which includes the changes from the linked PR.

The following video is taken on macOS. It shows that after closing the last window, the queries and history on both tabs that were open are still there after we close the window via the "red dot" and re-open by any of the following:

1. Clicking the app icon in the dock
2. Clicking **File > New Window** from the drop down menu
3. Right-clicking the app icon in the dock and selecting **Quit**, then restarting the app

https://user-images.githubusercontent.com/5934157/217401980-d0593ec8-7bce-402f-9243-e7796d90dd55.mp4

Likewise, the following videos show that queries/history are similarly preserved on both Linux and Windows when the last app window is closed via the "X" in the upper-right and then the app is relaunched.

https://user-images.githubusercontent.com/5934157/217403067-9a2a3ed7-7f7d-4e2e-863d-4daa88ec3f8c.mp4

https://user-images.githubusercontent.com/5934157/217403791-a7fbf5b9-1178-430c-9dd2-23d62882aa23.mp4

It has been noted that an even more deluxe enhancement we could one day offer here would to provide a sidebar to manage sessions such that their contents could always be preserved by default regardless of whether a window closed is one of many or the last one. This is tracked in #2467.

Thanks @jameskerr!
