### ISSUE TITLE
typeof() result not shown for primitive types

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1819]
Repro is with Brim commit af1f358 using test pcap https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz. The issue was originally reported by @mccanne.

As shown in the attached video, the value of `stringType` is not being shown in the app for queries that return primitive types, such as:

```
_path=="conn" | head 1 | cut stringType := typeof(_path)
_path=="conn" | head 1 | cut stringType := typeof(orig_bytes)
```

However, it _does_ print the output for an complex types, such as:

```
_path=="conn" | head 1 | cut stringType := typeof(id)
_path=="dns" | head 1 | cut stringType := typeof(answers)
```

When equivalent queries are issued via `zapi` against the same pool, the `stringType` value is output in all these cases.

https://user-images.githubusercontent.com/5934157/132591280-f1f7f7b1-7fd7-4c21-a529-01b7ee50b194.mp4

**Comment by mccanne** [comment]
This should be easy to fix and I run into it all the time.   I vote we elevate priority here.

**Comment by philrz** [comment]
Verified in Brim commit bf49c8c.

As shown in the attached video, now when the repro steps are repeated the primitive types such as `string` and `uint64` are shown where they weren't before.

https://user-images.githubusercontent.com/5934157/135343677-e37ea36d-06cf-4f90-8cc1-16be0e97dfb8.mp4

Thanks @jameskerr!
