### ISSUE TITLE
Enhance the UX for saving a named query

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1843]
When @mccanne was recently working in the Brim app after a prolonged absence, he had this question/observation:

> Newbie question.  How do you save a named query?  UX cues where the “…” drop-down in the query bar and the “Query” menu at the top.    Or maybe there would be a “+” on the query listing in the left panel.  None seemed present. (edited) 
> 
> Doh!  The star.

So, he figured it out, but struggled a bit along the way. Looking at it now as a user, one improvement that might help would be to add a tooltip when the user hovers their mouse pointer over the star (or for that matter, the thumbtack, the vertical "..." menu, the magnifying glass, etc.) so the user doesn't have to click on these things to confirm what they do.

Since we already have a "Query" pull-down menu, perhaps a "Save Query" option could be added there? If the star icon remains, it would be redundant of course, but this might increase the user's chance of finding one or the other.

Beyond that, maybe the choice of a star icon and its location could be improved. I don't claim to have the right answer, but once again trying to see it as a new user might, a brief query, the star icon, and the Queries list are all pretty far apart from each other, so it might not be entirely obvious how they're connected.

![](https://user-images.githubusercontent.com/5934157/134104548-8c2d11c0-2a49-4d7f-b8f2-7a35e49666e5.png)

**Comment by jameskerr** [comment]
This is great. Thanks for the write up Phil. I agree and will summarize your suggestions:

1. Add a "Save Query" option in the App Menu bar.
2. Move the star icon to a button clearly labeled "Save" located somewhere above the search bar. Maybe in the toolbar (designs pending)
3. Add tooltips to icons that don't have a label.

**Comment by jameskerr** [comment]
If the sidebar design stays the same, we could add a "plus" in the same place the "Pools" section has a plus. That could either open a new tab with a blank query, or it could open the new query form. 

Thinking about this more, I don't think we should have a save queries form. The Search bar is the form. No point duplicating everything in the search bar in another form. @mason-fish does this make sense to you?

**Comment by mason-fish** [comment]
I think some of the higher value features the form provides is the ability to name your saved query as well as annotate it with tags, so the form makes sense to me.

The plus button sounds good, though there is already the tags filter in the UI and I think we had ideas to include a search bar (for searching through queries) there too at some point. Maybe to save real estate and allow for future features, we also use a similarly sized icon as the plus for the filter so that we end up with little side bar section toolbars in their headers. WebStorm has a similar ui in some of it's sidebars fwiw

**Comment by jameskerr** [comment]
That is a good point about saving the tags and being able to name it. That would have to be considered if we made the search bar the form.

**Comment by mason-fish** [comment]
This ticket is being addressed by the new query flow, where all searches are a new "draft" query, and can be easily saved/promoted to a named query, all inline with the search bar.
