### ISSUE TITLE
vertical values in log view

### ISSUE THREAD

**Issue by mccanne** [brimdata/brim#1851]
It should be easy to pivot between a horizontal "log like" view of data values (as is currently implemented in the log view) and a vertical "pretty -Z" style of data values.

The vertical value cells would have precisely the same formatting and styling as the horizontal value cells but would be displayed in an indented arrangement as with `zq -Z`.

There are many examples of JSON viewers out there that have collapsable views of embedded records. A lot of these UIs are poorly designed but the idea of collapsable elements is important especially for large, complex nested values. We could start out without any collapse-ability and add this functionality in a subsequent issue.

_Side note: we should have a new name for the "log view". Perhaps the "data view"? Or the "data browser"_

**Comment by jameskerr** [comment]
The "results view". The "table view"?
