### ISSUE TITLE
Brim App UX Error when using fuse command

### ISSUE THREAD

**Issue by x62smith** [brimdata/brim#1855]
I used shaper to take in a json file to load into Brim via zed.  Once the data was loaded into Brim I used the fuse command to show all of the header fields.  I happened to click on a field and the result was the screenshot provided.  I haven't ran into this issue with any other types of data that I've loaded into Brim, whether it's from Zed or loaded into Brim directly.

**To Reproduce**
Load the provided results.zng file into Brim and use the fuse command.  Click on an ip address and it should show the error provided in the screenshot.  There are other values that will produce the same result, not just the IP addresses.

![Screen Shot 2021-09-29 at 5 33 37 AM](https://user-images.githubusercontent.com/19314872/135298134-2b6a8b1b-4267-4557-a303-1fd943467b5b.png)

**ZNG File**
[results.zng.zip](https://github.com/brimdata/brim/files/7253059/results.zng.zip)

**Desktop Info**
 - OS: MacOS
 - Brim Version: 0.25.0

**Comment by philrz** [comment]
I've confirmed the repro steps also trigger the problem in more recent Brim commit bf49c8c.

Thanks for filing @x62smith! We have a release currently planned for Monday, so we'll see if we can maybe look at getting this fixed before then.

**Comment by philrz** [comment]
Verified in Brim commit c52ee3e.

As shown in the attached video, now when following the repro steps, I can click on the IP address value without triggering a crash.

https://user-images.githubusercontent.com/5934157/135879296-efa9263b-7fa1-460e-8431-4bdd219ebad1.mp4

Thanks @jameskerr!
