### ISSUE TITLE
Query Library Tweaks

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1899]
- [x] Disallow folders to be dragged into themselves
- [x] Remove hover state
- [x] Add a drag over state to folders that is different from items
-  [x] There should be no persisted selection state. The only time we should highlight the row blue should be on multi-selection, when the command key is held down. (we change this when we are "in" a query)
- [x] Use the carrot icon for the folders instead of the triangle
- [x] When clicking new folder, scroll to it, and make it immediately editable
- [x] Make the readonly queries not draggable/droppable
- [ ] Add a lock icon to indicate readonly

**Comment by philrz** [comment]
I see that of the original checklist that kicked off this issue, there's already a separate open issue #1928 that covers the only one above that's still unchecked. Also, I opened #2542 to track the idea from @mattnibs in the comment above.

With that, I'll go ahead and close this issue as completed.
