### ISSUE TITLE
No data being exported after updating to Brim 0.26.0

### ISSUE THREAD

**Issue by plbarber** [brimdata/brim#1905]
**Describe the bug**
After updating to 0.26.0, I am not getting data when I do an export from the main Brim screen.  It looks like it's exporting but when you open the export file you see this: {"type":"Error","kind":"invalid operation","error":"mime: no media type"}

You get this output whether you choose ndjson, zng or csv as the output format

If I uninstall .0.26.0 and install 0.25.0, I can successfully export again.

**To Reproduce**
From the main screen, click the activity overview query.  Once the data populates on the screen, click the export button at the top of the page and select the export format(csv) and chose a file location and name.  It appears to export but when you open the export file the only output you see is: {"type":"Error","kind":"invalid operation","error":"mime: no media type"}

This seems to happen no matter what query you use and try to export the results.

**Expected behavior**
In 0.25.0 you get an export of the data showing on the screen

**Screenshots**
Error message in export file - {"type":"Error","kind":"invalid operation","error":"mime: no media type"}

**Desktop Info**
[Please complete the following information]
 - OS: I have gotten the error from a windows 7 and windows 10 PC
 - Brim 0.26.0

**Comment by plbarber** [comment]
Thank you for your help and quick response. (We don't get this response
time on paid apps)

Also thanks for the workaround, very much appreciated.

**Comment by jameskerr** [comment]
Thanks @plbarber ! We didn't get the release out yesterday, but it will come shortly with this fix included.
