### ISSUE TITLE
sub-menu bug from read-only item to regular item

### ISSUE THREAD

**Issue by mattnibs** [brimdata/brim#1907]
**Describe the bug**
If I have a read-only query item selected then I select a regular item and then activate the sub-menu, the sub-menu initially does not let me rename/edit/delete. If I close the sub-menu and reopen it then allows me to rename/edit/delete.

**Screenshots**
![read-only bug](https://user-images.githubusercontent.com/2147549/139466095-956a1655-3172-41fe-a44b-3c44612b7487.gif)

**Desktop Info**
 - OS: macOS
 - Brim Version: v0.26.0-69-gafd04fbc

**Comment by jameskerr** [comment]
@mason-fish I think we should fix this one too before the release.

**Comment by mason-fish** [comment]
@jameskerr sorry, re-opening this to focus on the remaining issue where folders allow right click options that only make sense for queries. I thought there was another ticket for that bug but I think this is it.

**Comment by nwt** [comment]
I've verified that this is fixed in the v0.27.0 release.
