### ISSUE TITLE
Can't import a csv file into the app

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1913]
If you try to drag a csv into the app you get this error: 

<img width="414" alt="Screen Shot 2021-11-01 at 10 13 09 AM" src="https://user-images.githubusercontent.com/3460638/139711921-e9a5d920-2144-4a51-ace9-f9a6bbb4e091.png">

Since the backend supports it, we should enable a csv to be dragged into the app.

A possible workflow is:

1. Import the file
2. If there is an auto detect error, prompt the user for the type of file

**Comment by philrz** [comment]
FYI, I think this is working now. The attached video shows me successfully importing a CSV file with Brim `v0.28.0`.

https://user-images.githubusercontent.com/5934157/144133400-788929f1-54a8-458b-9cca-81b85c07d269.mp4

**Comment by jameskerr** [comment]
I'd love a dialog that asks the user which format their data is in to pass to zed load. I've got a csv that it things is zson so it fails with a strange error.

It would also be nice to give a summary of what the auto detect detected.

**Comment by philrz** [comment]
Since the original spirit of this issue has morphed somewhat, I've opened #2498 to be clearer about where things stand currently. Closing this one since for the general case of importing true CSV into the app, it does indeed work now.
