### ISSUE TITLE
Make pools section droppable

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1914]
When I was creating a lot of new pools, it was annoying to have to click the plus button each time. I want to be able to drag the file right onto the pools section of the side bar and ingest it.

Make this droppable 👇
<img width="221" alt="Screen Shot 2021-11-01 at 10 18 51 AM" src="https://user-images.githubusercontent.com/3460638/139712865-b3982427-26bf-4002-b440-f99aff796653.png">

**Comment by mattnibs** [comment]
Verified that I get a lovely import animation when I drag a zson file into the pools section (Brim v0.28.0). I did notice that if I dropped that same zson file into the queries section, nothing happens in the app but I do get a console error:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/2147549/142676346-41b10dce-4de0-4532-8d49-ef493516caca.png">

Maybe there should be an error if you drop a bad file into the queries section? You do get an error if you drag a bad file into the pools section.
