### ISSUE TITLE
Packets button needs padding on top

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1916]
In the log detail window:

![image](https://user-images.githubusercontent.com/3460638/139716884-76d848ac-def8-48ea-b026-9ca0385710df.png)

**Comment by nwt** [comment]
I've verified this in the v0.27.0 release as shown in this screenshot.

![image](https://user-images.githubusercontent.com/2574448/140532033-f75cb068-a80d-45ba-9f35-002febe07e43.png)
