### ISSUE TITLE
Rename "Workspace" and "Lake"

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1922]
We used to call "lakes" "workspaces" and we used to call "pools" "lakes". It's very confusing in certain files to see the names switched up. This ticket is a reminder to rename all those files, functions and variables. 

We should also write a migration to change all the URLs stored in the tab histories state, because the urls have the words "workspace" and "lake" in them too.

**Comment by mccanne** [comment]
I also noticed that the list of workspaces goes away on restart.  They should be persistent.  I think of them like slack teams.  You shouldn't have to rejoin your slack teams every time you restart the app.

**Comment by mccanne** [comment]
> I also noticed that the list of workspaces goes away on restart. They should be persistent. I think of them like slack teams. You shouldn't have to rejoin your slack teams every time you restart the app.

I realize the app implements the correct behavior in terms of keeping the connection list around but  I think it got removed when the service went down.  We should look into this.

**Comment by jameskerr** [comment]
@mason-fish this is all done now?

**Comment by mason-fish** [comment]
@jameskerr Yep!
