### ISSUE TITLE
Unable to deselect multiple queries

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1924]
When using the new query library to select multiple queries, you can't deselect them by clicking the outside of the list. The listener should just be on the containing div.

![image](https://user-images.githubusercontent.com/3460638/139926116-41561dfc-c58d-4076-b584-82c101aa2c71.png)

**Comment by philrz** [comment]
Verified in Brim commit a6fc1a8.

As shown in the attached video, now if I select multiple queries in the list, then click elsewhere in the queries area, the previously-highlighted entries are deselected.

https://user-images.githubusercontent.com/5934157/198719067-9ddb7581-8a27-44e6-b628-58ca93bb5dcc.mp4

Thanks @jameskerr!
