### ISSUE TITLE
Multi-selecting issues queries for each item selected

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1925]
Multi selection still issues the queries that you are selecting. We should only run the search if they click on the query without the meta or shift key held.

https://user-images.githubusercontent.com/3460638/139926684-01918270-ef8d-45de-8684-6c39b8c8e81e.mp4

**Comment by mattnibs** [comment]
Verified this works! When I hold a meta key (i.e command or shift) the query is no longer run.
