### ISSUE TITLE
Drag and drop bugs around readonly folders

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1927]
There are two issues to solve:

1. I can't drag an item above the readonly folder if that folder is the first in the list.
2. I can't drag the readonly folder itself to a different spot in the tree.

Both of these should be possible:

https://user-images.githubusercontent.com/3460638/139927771-a0cdf52f-9774-43e9-a5e3-9145931ef976.mp4

**Comment by mattnibs** [comment]
Tested on v0.27. I verified the first part- I can drag any item above a readonly folder. The second part doesn't work- I cannot drag a readonly folder wherever I want in a tree.
