### ISSUE TITLE
app display of large array values overwrites itself

### ISSUE THREAD

**Issue by mccanne** [brimdata/brim#1950]
Easy to reproduce problem with array values.

Create a file `bug.zson` with an array:
```
{ a:[
  "four score",
  "and 7 years ago",
  "our father brought forth",
  "on this continent",
  "a new nation" ] }
```
Load this file into a space and then look at the data with the app....
```
zapi create Bug
zapi load -use Bug@main  bug.zson 
```
then look at the pool in the app and you get....

![Screen Shot 2021-11-10 at 12.46.23 PM.png](https://images.zenhubusercontent.com/5eb71987b2047c8f0c7cb79d/430a3e41-39a8-4a65-be63-de7445fda64b)

**Comment by mattnibs** [comment]
Verified the text is no longer overlapping as of v0.28.0. Nice!
![image](https://user-images.githubusercontent.com/2147549/142672094-403e6acf-471d-4f82-a82e-f8818a026cb8.png)
