### ISSUE TITLE
Dragging query JSON into Brim when there's no pools looks like a no-op

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2038]
Repro is with Brim commit 00ad8da.

When following the cloud bootstrapping steps at [https://github.com/brimdata/cloud/blob/main/README.md](https://github.com/brimdata/cloud/blob/main/README.md) as a user, I'm encouraged to drag the `queries.json` file into the app. However, as shown in the attached video, if the app is starting out "blank" with no pools (which was the case for my cloud instance when it was first set up), I'm shown the "Imported Welcome" pop-up that implies success, but there's still no entries visible in the Queries panel. As @mason-fish later explained:

> I think what's happening is that the lib IS importing but whenever you don't have a pool selected, the query lib section of the left sidebar is in the state where it says "You must have a pool selected to run queries." so it is not visible. I agree this is not intuitive, and the instructions should make this clearer.

Indeed, since many users are bad at reading instructions, I'd take this one further and suggest that the query import be rejected if the imported queries can't be made immediately visible, because I sense the perception of a no-op is always going to look like a bug to a user. In any case, the video shows @mason-fish's statement to be correct: Once I imported some data which created a pool, the imported queries are shown to have actually been present, but just not yet visible.

Three additional thoughts (haven't opened separate issues for these):

1. The instructions at https://github.com/brimdata/cloud/blob/main/README.md spoke of "Welcome pools", and indeed, if there had been at least one pool present when I first connected to my cloud instance, I'd not have hit this bug. If the cloud provisioning tools are not going to start including these pools, I'd suggest removing the reference in the README.

2. The cloud README also claims: "You may also import this file by clicking on the + button in the Queries panel and selecting Import from JSON". But once again this "+" is not visible until a pool is present, so the app and the instructions are out of sync.

3. The pop-up "Imported Welcome" reads a little funny to me. Maybe I'm in the minority by preferring verbosity, but I'd opt for something like: `Imported query set "Welcome"`

https://user-images.githubusercontent.com/5934157/148834669-67afeaad-c29e-4469-9c1b-24ff6a91d251.mp4

**Comment by jameskerr** [comment]
@mason-fish did you address the queries not being visible unless you have a pool selected in your remote queries branch? I thought I may have seen something related to that.

**Comment by mason-fish** [comment]
@jameskerr Nope, but this will all change with the new query-focused flow we're implementing now. After that, the notion of selecting a pool will be a different ux and not a prerequisite for running queries so folks won't run into this.

**Comment by philrz** [comment]
I've verified that this was fixed some time ago. In the attached video taken with Brim commit 290f138, we see that dragging the query JSON into Brim when there's no pools does populate the queries list and hence is no longer a no-op.

https://user-images.githubusercontent.com/5934157/185433519-83a6640e-5b7c-4f5c-988e-0853c83f881a.mp4

Closing as fixed.
