### ISSUE TITLE
Flaky Test: Zed Events Spec

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2135]
I am not sure the cause of this failure:

https://github.com/brimdata/brim/runs/5100228293?check_suite_focus=true

**Comment by philrz** [comment]
@jameskerr: The logs from that Actions run are no longer accessible. Do you recall the detail from memory or recall having seen it happen again recently? If not, maybe we should close this and plan to capture the detail next time it happens.

**Comment by jameskerr** [comment]
I have not seen this being flakey lately. So I'll close this.
