### ISSUE TITLE
Relative dates show "dirty" state

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2183]
When there is a relative date in the time picker, the two blue dots that indicate a dirty state never disappear. 

<img width="262" alt="Screen Shot 2022-02-16 at 3 37 56 PM" src="https://user-images.githubusercontent.com/3460638/154375794-d75dda50-1c37-4d7e-9a88-31b8aef0490b.png">

**Comment by philrz** [comment]
The time picker as described here is no longer part of the current Zui experience, so I've cleared with @jameskerr that we can close this one as no longer relevant.
