### ISSUE TITLE
Export to zng creates missing errors

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2190]
This is maybe not a bug, but certainly undesirable behavior. Watch the video to reproduce.

The issue is that when you export the results while having some columns selected with the column picker, you end up with missing errors.

The solution may be to change the query we make when exporting.

https://user-images.githubusercontent.com/3460638/154568060-e5759414-44e8-424a-a1e6-3ea273c7cc32.mov

**Comment by philrz** [comment]
@jameskerr: Yes, I think you're correct that a query change is justified.

I could see from looking at the code:

https://github.com/brimdata/brim/blob/ef478a4075222e9b966b69fa1ce2c84e20d0a7b9/src/js/flows/exportResults.ts#L14-L24

...that when columns are selected, it's doing a Zed `cut()` to isolate those fields. Per the [Zed `cut()` docs](https://zed.brimdata.io/docs/language/operators/cut), if those fields aren't present, it'll populate those values with `b:error("missing")`. And the way to shut that off is with [`quiet()`](https://zed.brimdata.io/docs/language/functions/quiet).

Here's an example using the [sample.zng](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.zng) from this repo that shows how the problem surfaces at the Zed layer. The following query isolates two Zeek log types and does what the current column chooser Zed does for a field that's in both log types (`_path`), a field that's only in one of them (`id`), and a field that's in neither (`foo`).

```
$ zq -Z '_path in ["ssl", "x509"] | cut _path,id,foo' sample.zng
{
    _path: "x509",
    id: "FMY9Or1CoNOROvmg1i",
    foo: error("missing")
}
{
    _path: "ssl",
    id: {
        orig_h: 192.168.1.110,
        orig_p: 57640 (port=uint16),
        resp_h: 209.216.230.240,
        resp_p: 443 (port)
    },
    foo: error("missing")
}
```

And if we wrap each field reference with `quiet()`, we get what I think you're seeking.

```
$ zq -Z '_path in ["ssl", "x509"] | cut quiet(_path),quiet(id),quiet(foo)' sample.zng
{
    _path: "x509",
    id: "FMY9Or1CoNOROvmg1i"
}
{
    _path: "ssl",
    id: {
        orig_h: 192.168.1.110,
        orig_p: 57640 (port=uint16),
        resp_h: 209.216.230.240,
        resp_p: 443 (port)
    }
}
```

**Comment by philrz** [comment]
Verified in Brim commit 1d61783.

As shown in the attached video, now when we export with a subset of columns selected that includes missing values, there's no longer `error(missing)` values in the exported data.

https://user-images.githubusercontent.com/5934157/188204589-caa1f1fd-51e1-4323-8146-a4b2fbae527d.mp4
