### ISSUE TITLE
Scroll to sidebar item after creation

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2199]
When creating a new query, dragging a query library, create a pool or dragging a pool, we must scroll the sidebar to that item.

**Comment by philrz** [comment]
Verified in Brim commit a6fc1a8.

As shown in the attached video, now when the user takes each of these actions, the left sidebar automatically highlights the appropriate entry. This makes it easy for a user that wants to immediately hit Enter or click it to start renaming it, if desired.

1. Creating a new query by typing a name and clicking **Save** in the area above the editor
2. Creating a new pool by clicking **New Pool**
3. Creating a new pool by dragging it into the **Pools** list
4. Dragging in a query library JSON
5. Creating a new query by right-clicking in the **Queries** area and selecting **New Query**

https://user-images.githubusercontent.com/5934157/198713815-dce02e9c-6d75-4678-b449-853c873929b7.mp4

Thanks @jameskerr!
