### ISSUE TITLE
Query Flow

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2216]
This is the container for all the issues we need to close before we can remove the query-flow feature flag.

**Comment by philrz** [comment]
The Query Flow effort has been deemed complete. The feature flag we had for Query Flow (start the app via `yarn start --feature-flags=query-flow`) has been removed. The next design effort is dubbed Session Flow and is tracked in new epic #2430. The couple of remaining issues that were still attached to this epic that are relevant to Session Flow have been moved over. Closing this one.
