### ISSUE TITLE
UX for a saved query that can run on any pool

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2224]
There is no doubt that we will want to save a query and run that query on several different pools. If the pool name is hardcoded in the query, that makes it annoying as you have to change it each time.

We need to save the queries to be pool independent, then have a way for them to switch the pool.

It would also be cool to be able to drag a query onto a pool and have it do the right thing.

Maybe you just save the query with a pool pin if you want that behavior. As you change the pool and the query it automatically updates.

This might be easy if we save the pins and the pin's type in the saved query it self. The parameters become the pins. We could make all sorts of pins that can be changed in isolation. This could be a way to do parameterized queries.

**Comment by mason-fish** [comment]
closing since we've decided that the new from-pin picker can offer the desired functionality
