### ISSUE TITLE
Sidebar hide/show

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#2241]
We still need to add a button to show/hide the left sidebar and right pane (maybe just call this the right sidebar moving forward?). Only way to do this now is through hotkeys and app tray menu.

**Comment by philrz** [comment]
As of today, @jameskerr has shown some designs that include buttons to show/hide these. However, as @mason-fish also notes:

> we do still need a design for what it looks like in a collapsed state. With that and also the icon svg I can knock that out fast.

**Comment by philrz** [comment]
Verified in Brim commit 6ea3f6a.

Now in addition to the existing hotkey combo (Cmd-[ on macOS, Ctrl-[ on Windows/Linux), the button shown in the attached video can also be used to toggle the left side panel.

https://user-images.githubusercontent.com/5934157/179641933-dd93fbef-8068-482e-bff8-07b736396a62.mp4

Thanks @mason-fish!
