### ISSUE TITLE
Better query errors

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2246]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/3460638/156857481-fb582828-0214-4991-ac94-18607527d5bb.png">

When the backend returns an error, we show this catastrophic pop up error. It needs to be more subtle.

**Comment by philrz** [comment]
@jameskerr: For the example in the initial issue text, the following video shows that as of Zui Insiders `0.30.1-50` it is indeed more subtle. Do you think we can close this issue, or do you have something more ambitious still in mind?

https://user-images.githubusercontent.com/5934157/186047931-5547857e-777b-4d3c-a8b1-789aab25639c.mp4

**Comment by jameskerr** [comment]
Yes! This has been addressed well enough to close this ticket.
