### ISSUE TITLE
Query Flow Submit Bug

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2248]
Have the query flow feature flag eneabled. 

I opened a query and hit "ENTER" multiple times in fast succession and got this. 

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/3460638/156859349-f1683a84-0a89-4d32-9cf1-4718b799061b.png">

**Comment by philrz** [comment]
This feature flag is long gone and the Session Flow redesign has changed many things, so I'd like to assume this one has been fixed along the way. However, I just tried to reproduce this one with a couple commits from March 4, 2022 and was not able, so I don't have a way to verify it's gone. I've asked @jameskerr if he has any memories of the magic repro recipe, and if not, perhaps we should close.

**Comment by jameskerr** [comment]
This has been fixed Phil. We no longer rely on the "span" when issuing a query. Thanks!

**Comment by philrz** [comment]
Closing per last comment from @jameskerr.
