### ISSUE TITLE
Preview Tab

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2273]
If you run through and click every single query in the sidebar, you'll get a new tab for each one. This might not be what you want if you are just clicking through the queries to see what they are. Let's make it so that.

1. a single click creates a tab in a preview mode. The tab will be reused (or destroyed and recreated) if the user clicks another item in the sidebar. We can indicate it's in preview mode by making the title italic.
2. A double click opens a tab normally like today

**Comment by philrz** [comment]
@jameskerr: I noticed a related oddity while experiencing this just now in Brim commit aac7f4b. As shown in the attached video, as I clicked each query entry, I noticed that for every other one there was no Zed query populated into the search bar and the text at the top of the window indicated the query was "Modified". This was on a fresh run of Brim with no prior changes to app state. I wasn't sure if this justified its own issue so figured I'd start by just mentioning it here.

https://user-images.githubusercontent.com/5934157/161842454-4dba6600-9cae-4b9f-ab41-a5ae84df67b7.mp4

**Comment by jameskerr** [comment]
@mason-fish tagging you here so you can see Phil's discovery above.

**Comment by mason-fish** [comment]
Hmm, yeah that's a bug. And a peculiar one at that, given it's toggling nature. I think I'll fix that on its own since we may want to discuss this ticket's feature a bit more.

**Comment by jameskerr** [comment]
I'm currently working on this.
