### ISSUE TITLE
Support non-ts pool keys

### ISSUE THREAD

**Issue by mattnibs** [brimdata/brim#2283]
If I create a pool with a pool key that isn't named ts, the app fails to show any data.

Steps to reproduce:

1. create pool with a non-standard pool key
```bash
$ zed create -orderby created_at:desc prs
```
2. add data
```bash
$ zq https://api.github.com/repos/brimdata/zed/pulls\?state\=all\&sort\=desc\&per_page=100 \
| zed load -use prs@main -
```

3. Run zed serve:
```bash
$ zed serve
```

4. Open Brim and observe that you don't see any data:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/2147549/159503485-dff669b3-debc-4579-9d04-ad29127ddb74.png">

Brim appears be issuing a query that assumes the Pool key is `ts` when in this case it is the field `created_at`.

Observed in the dev console:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/2147549/159503963-2f875589-6173-431e-a362-4719c9ae3e2f.png">

**Comment by jameskerr** [comment]
Thanks Matt. Will fix
