### ISSUE TITLE
Non optimized range queries on Pools

### ISSUE THREAD

**Issue by mattnibs** [brimdata/brim#2284]
The brim client appears to be running non-optimized range queries against a zed lake.

Observed in the dev console:

![image](https://user-images.githubusercontent.com/2147549/159504448-bbab0218-fb40-47c1-ace8-c169b1a9c229.png)

The optimized query should look like this:

```
from '0x0ec6879805196963e1affcc04fbe84e0c1e65702' range 2019-11-11T19:50:46.000Z to 2021-08-10T19:48:56.000Z | * | head 50
```

**Comment by jameskerr** [comment]
Did not know this! Thanks!

**Comment by mattnibs** [comment]
Eventually we'll have the backend optimize what you have. I'll create a ticket for this on the zed side.

**Comment by philrz** [comment]
Oops. I just opened #2449, not realizing this already exists. When I was writing it I pointed at the imminent arrival of https://github.com/brimdata/zed/pull/3930, so I'll close this one as a duplicate.
