### ISSUE TITLE
Pull-down menu is missing on Windows

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2287]
I installed the most recent nightly Windows build based on commit f4152a70 and noticed the pull-down menu is no longer present, as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/5934157/159974020-3ef19ac9-fb9b-46dc-8641-bb7df007e3ed.png)

Contrast with the last GA v0.28.0:

![image](https://user-images.githubusercontent.com/5934157/159974044-66c79649-b36c-4248-ad70-0cb0b7a27190.png)

**Comment by jameskerr** [comment]
Thank you @philrz , this may be the result of an electron upgrade. I expect to have a fix up before lunch.
