### ISSUE TITLE
Query Fetching Spinner

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2385]
Design and build.

**Comment by philrz** [comment]
I've verified in Brim commit b282d7a that this was added as part of the changes in #2433.

As shown in the attached video, now as queries are executing, the status bar at the bottom of the window says "Fetching" with a spinner. The same status bar also shows the count of how many records and shapes are within the fetched results, and these change as the user scrolls down to look for more rows of a large query result.

https://user-images.githubusercontent.com/5934157/179873195-03cbffda-4a81-4683-be04-e5375e336426.mp4

Thanks @jameskerr!
