### ISSUE TITLE
Make pin management closer to the pins

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2386]
Design needed

**Comment by philrz** [comment]
Verified in Brim commit 124d658.

As shown in the attached video, the pin selector is now very close to where the cursor starts out in the editor, which hopefully will help draw the user's attention to its availability and significance. The inactive, dotted-line-surrounded "from" pin that's present when there's not already an active From Pin is also added here and should help. Finally, the Run button (the one that looks like a "Play" button from a tape recorder) has been moved up to the bar above the editor.

https://user-images.githubusercontent.com/5934157/190290398-ca474bd2-a9cf-49ca-9946-1d1de83af4ca.mp4

Incidentally, the move of the Run button did break the e2e tests. Fixing that is tracked in #2534.

Thanks @jameskerr!
