### ISSUE TITLE
Create a simple welcome page

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2387]
This would be a page to greet new users on first ever Zui launch in lieu of some of the existing pages such as Release Notes or Import Files. It would include app links and web links for common tasks.

Strictly speaking we may not need this for Zui v1.0 since we've been thinking the top priority is to GA Zui when we have feature parity with the prior Brim app. However, it'd very much be a nice-to-have, so it's in our v1.0 goals for now.

**Comment by jameskerr** [comment]
![image.png](https://images.zenhubusercontent.com/5e8cea85d10cba8a99efeb34/7207a78d-bbc2-407c-ae5d-11d4882cedfa)

**Comment by philrz** [comment]
Verified in Brim commit 0752fdb.

In the attached video the Zui app is launched as if for the first time. The new welcome page is presented and each of the two links initiates the expected workflow.

https://user-images.githubusercontent.com/5934157/188745411-1246fac4-4990-4394-9b95-de188dbcaaaf.mp4

Thanks @jameskerr!
