### ISSUE TITLE
connCorrelation query misses Suricata alerts due to timestamps (regression at b819d7e)

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2443]
Repro is possible with current Brim commit b282d7a, though a binary search has confirmed that the problem was a regression starting at commit b819d7e.

To repro, drag the common "all.pcap" test data into the app and query for `"1:IK50rOTNQcdxeBERZDmdl/D3z7c="`, which is a Community ID for a flow that's known to be associated with many Zeek events and Suricata alerts. The main results window does indeed show the many `alert` events alongside the Zeek `conn` log, but the Correlation visualization in the side Detail panel doesn't show any `alert` tiles.

![image](https://user-images.githubusercontent.com/5934157/179327537-4861f829-f7e2-43e7-8da1-3ac3e0eb4760.png)

By sniffing in Wireshark I could see the query being crafted by https://github.com/brimdata/brim/blob/main/src/js/searches/programs.ts and sent to the backend Zed API looks like:

```
{"query":"from 0x0f5fa8605ca618bf66b91542519d763d534ad2ac | uid==\"CKViDSjhtOHgqDUN1\" or \"CKViDSjhtOHgqDUN1\" in conn_uids or \"CKViDSjhtOHgqDUN1\" in uids or referenced_file.uid==\"CKViDSjhtOHgqDUN1\" or (community_id == \"1:IK50rOTNQcdxeBERZDmdl/D3z7c=\" and ts >= 1428413683.772 and ts < 1428413779.68) | head 100"}
```

The problem is with the `ts` timestamp comparisons. Brim commit b819d7e marked the point where it started using a Zed backend that had the change from https://github.com/brimdata/zed/pull/3809, which was when Zed `time` values that are converted from numbers started being interpreted as epoch nanoseconds rather than being scaled from epoch seconds to nanoseconds automatically. So to make this work, one could multiply the numeric times by 1-billion:

```
$ zed query -z 'from all.zng | uid=="CKViDSjhtOHgqDUN1" or "CKViDSjhtOHgqDUN1" in conn_uids or "CKViDSjhtOHgqDUN1" in uids or referenced_file.uid=="CKViDSjhtOHgqDUN1" or (community_id == "1:IK50rOTNQcdxeBERZDmdl/D3z7c=" and ts >= 1.428413683772e18 and ts < 1.42841377968e18) | has(event_type) | count()'
{count:20(uint64)}
```

Or express them as ISO8601 timestamps:

```
$ zed query -z 'from all.zng | uid=="CKViDSjhtOHgqDUN1" or "CKViDSjhtOHgqDUN1" in conn_uids or "CKViDSjhtOHgqDUN1" in uids or referenced_file.uid=="CKViDSjhtOHgqDUN1" or (community_id == "1:IK50rOTNQcdxeBERZDmdl/D3z7c=" and ts >= 2015-04-07T13:34:43.772Z and ts < 2015-04-07T13:36:19.68Z) | has(event_type) | count()'
{count:20(uint64)}
```

Related question: Would there be an easy way to audit the code and find other places where the app might still be generating queries with time values that depend on the old scaling behavior? We've been bitten by this Zed change in a couple places now and it would be a drag to keep having to find them all whack-a-mole style.

**Comment by jameskerr** [comment]
Phil, thank you for this issue. This was actually known and referenced in this PR description which fixed it for the exports in the app 10 days ago: https://github.com/brimdata/brim/pull/2427. It is much better that it's in this issue now.

**Comment by philrz** [comment]
Verified in Brim commit 3e0bfbc.

As this screenshot shows, after following the original repro steps, we now see the many Suricata alerts linked to this `conn` record.

![image](https://user-images.githubusercontent.com/5934157/180617766-8a0f425d-b194-4d07-966b-dee9a88540cb.png)

Thanks @jameskerr!
