### ISSUE TITLE
Tooltip for clock icon

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2476]
Repro is with Brim a20f709.

As a user, I'd forgotten what the clock icon was supposed to do. At first I smashed on it several times and nothing visibly changed, so at first I wondered if there might have been a bug. Then I remembered that it had something to do with the right panel. As shown in the attached video, I ultimately deduced that it seems to have the purpose "Open the History tab on right panel", which explains why it was acting like a no-op when I already had the panel open & on that tab. Assuming this is the intended functionality, I think adding a tooltip saying something to that effect would be helpful in the event users get stuck in the same spot I was.

https://user-images.githubusercontent.com/5934157/183488626-df257ac6-f4fe-4423-a960-64b931356066.mp4

**Comment by jameskerr** [comment]
Agreed

**Comment by philrz** [comment]
Verified in Brim commit 6e55cd4.

As shown in the attached video, now hovering the mouse pointer over the clock icon does reveal a tooltip that explains what it's for. As a bonus, @jameskerr also made it such that if the button is pressed after the right sidebar is already showing Session History, it pulses with a yellow highlight to make it more obvious to the user what it's for.

https://user-images.githubusercontent.com/5934157/188755176-eb24abd4-e6e3-4420-a784-06c172a4f354.mp4

Thanks @jameskerr!
