### ISSUE TITLE
Hang on "Fetching" after adding a Time Range pin

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2483]
Repro is with Brim commit 1ee21a8.

To repro:

1. Import a test pcap (such as [sample.pcap](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.pcap) from this repo)
2. Add a "Time Range" pin (accepting the default start/end times is fine)
3. Execute the query

As shown in the video below, at this point it now hangs in "Fetching" status. A look in DevTools shows this stack dump when the query was executed:

```
13:57:23.670 › Security Warning: Prevented navigation to file:///Users/phil/work/brim/dialog?field=ts&from=2022-08-11T20%3A27%3A21.533Z&to=2022-08-11T20%3A57%3A21.533Z
consoleLog @ /Users/phil/work/brim/node_modules/electron-log/src/transports/console.js:91
transport @ /Users/phil/work/brim/node_modules/electron-log/src/transports/console.js:46
runTransport @ /Users/phil/work/brim/node_modules/electron-log/src/log.js:44
(anonymous) @ /Users/phil/work/brim/node_modules/electron-log/src/transports/ipc.js:21
emit @ node:events:394
onMessage @ node:electron/js2c/renderer_init:81
```

If I try to execute the query again, I get this different stack dump:

```
/Users/phil/work/brim/node_modules/history/cjs/history.js:871 Uncaught TypeError: Cannot assign to read only property '1' of object '[object Array]'
    at /Users/phil/work/brim/node_modules/history/cjs/history.js:871
    at Object.confirmTransitionTo (/Users/phil/work/brim/node_modules/history/cjs/history.js:168)
    at Object.replace (/Users/phil/work/brim/node_modules/history/cjs/history.js:869)
    at /Users/phil/work/brim/dist/app/router/tab-history.js:31
    at Object.dispatch (/Users/phil/work/brim/node_modules/redux-thunk/lib/index.js:11)
    at QueriesApi.dispatch (<anonymous>:3665:80)
    at QueriesApi.open (/Users/phil/work/brim/dist/js/api/queries/queries-api.js:97)
    at /Users/phil/work/brim/dist/app/query-home/flows/submit-search.js:35
    at Object.dispatch (/Users/phil/work/brim/node_modules/redux-thunk/lib/index.js:11)
    at dispatch (<anonymous>:3665:80)
```

https://user-images.githubusercontent.com/5934157/184241568-4321de51-9a4c-4d9a-bab2-456b4416051a.mp4

**Comment by jameskerr** [comment]
Got it. Thank you

**Comment by philrz** [comment]
Verified in Brim commit b08ceaf.

As shown in the attached video, now when the Time Range pin is added, the query re-executes as expected and we're now able to start manipulating the picker settings directly or by brushing the bar chart.

https://user-images.githubusercontent.com/5934157/187998753-0e552ca2-f6f9-4a98-8424-1423c315bdb3.mp4

Thanks @jameskerr!
