### ISSUE TITLE
"Pins" menu is empty when accessed via >>> 

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2484]
Repro is with Brim commit 1ee21a8.

As shown in the attached video, when the app window is narrowed such that the ">>>" pull-down appears, the "Pins" menu now shows "(empty)".

https://user-images.githubusercontent.com/5934157/184243203-ea57f040-60c9-4827-95bc-1b2f5de7ec59.mp4

**Comment by jameskerr** [comment]
Thanks Phil.

**Comment by philrz** [comment]
Verified in Brim commit 124d658.

As shown in the attached video, in its new location, the Pins menu no longer changes to ">>>" when the window is narrowed and continues to function normally.

https://user-images.githubusercontent.com/5934157/190444949-7f29e11c-7266-4832-ad5a-0a5fa578f61b.mp4

Thanks @jameskerr!
