### ISSUE TITLE
Right-click "Open details" feels like a no-op

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2537]
Repro is with Brim commit 124d658.

I was clicking through some current workflows in the app with intent to start recording videos as documentation. As I was going through all the current options on the right-click menu, I was struck by the sense that "Open details" felt like a no-op. This actually led me back to go back to GA Brim `v0.31.0` and remind myself what it looked like in the past. As shown in the attached video, I was quickly reminded that it simply opened the right-side "Log Details" panel, and of course the details for the clicked record would be shown there.

https://user-images.githubusercontent.com/5934157/190536876-616cc293-13e9-49e3-b1c1-2c6e989f2a20.mp4

However, compare this with what I experienced while pretending to be a brand new Zui user at commit 124d658 in this next video. Since the right panel is now open by default, clicking it after importing my first data appears to do nothing. Knowing what I know as an insider about what it did in the past, I then hit the hotkey to close the right panel and selected "Open details" once again. Indeed, this opened the right panel, but didn't even switch to the "Detail" tab within that panel. I had to click that manually as an extra step. Therefore, it's effectively a straight-up bug at this point.

https://user-images.githubusercontent.com/5934157/190537041-c35089e8-9455-4e16-9b49-9eca0bb56935.mp4

In terms of what we might make "Open details" do instead as a part of a fix, my first thought is that the separate "Details" window could be popped out, just like what happens when a record is double-clicked. Indeed, I suspect that the original panel-centric functionality of the right-click "Open details" might date all the way back to before the popped out "Details" window even existed, so this change might be overdue.

**Comment by jameskerr** [comment]
I think if the detail pane is open, this option should be disabled. But if the detail pane is not open, it should open the right pane and move to the detail tab.

I don't like buttons that can be clicked but don't do anything.

**Comment by philrz** [comment]
@jameskerr: That proposal works for me!

**Comment by philrz** [comment]
This one looks to be on track to be fixed by the changes in #2626. The attached video shows tests at commit 7bd659b from that branch. As it shows, now the text "Open details" has been replaced by "Show in Detail Pane" which is clearer about what it's intended to do. If we click it a second time when the selected record is already shown in the Detail pane, there's now a yellow pulse in the "Detail" tab heading which means it no longer feels like a no-op. Also, if the right pane is closed when on some other tab besides Detail, when "Show in Detail Pane" is selected, it re-opens to the Detail tab and shows the expected record.

https://user-images.githubusercontent.com/5934157/214716385-16dabea0-0a74-4519-b4c6-fca0b54d9eb0.mp4

**Comment by philrz** [comment]
Verified in Brim commit 499a2c9.

The attached video is effectively a repeat of what was shown in the most comment when testing on the branch. Now the text "Open details" has been replaced by "Show in Detail Pane" which is clearer about what it's intended to do. If we click it a second time when the selected record is already shown in the Detail pane, there's now a yellow pulse in the "Detail" tab heading which means it no longer feels like a no-op. Also, if the right pane is closed when on some other tab besides Detail, when "Show in Detail Pane" is selected, it re-opens to the Detail tab and shows the expected record.

https://user-images.githubusercontent.com/5934157/214938618-aa3be211-f525-4c78-becc-705927d39dc6.mp4

Thanks @jameskerr!
