### ISSUE TITLE
No error message displayed on json load exception (regression after GA Brim v0.28.0)

### ISSUE THREAD

**Issue by burpheart** [brimdata/brim#2554]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimdata/brim/wiki/Troubleshooting

**Describe the bug**
No warning message displayed on json load exception
Version 0.26 normally indicates a parsing error
**To Reproduce**
Loads a multi-line json file that has lines that cannot be parsed properly.
Brim only parses the data before the exception line, and there is no error message.

**Expected behavior**
Display a warning message about an engine parsing error.

**Screenshots**

**Desktop Info**
 - OS: Windows
 - Brim Version: 0.31.0

**Comment by philrz** [comment]
Here's a repro at Brim commit 6eaaa54 which uses Zed commit `28f95a3`.

The attached test data [threelines.ndjson.gz](https://github.com/brimdata/brim/files/9658986/threelines.ndjson.gz) used in the repro has a syntax error on the second line. Indeed, standalone Zed CLI tooling recognizes this.

```
$ gzcat threelines.ndjson.gz 
{"one": 1}
{"two : 2}
{"three": 3}

$ zq -version
Version: v1.2.0-64-g28f95a3c

$ zq -z threelines.ndjson.gz 
threelines.ndjson.gz: parse error: string literal: unescaped line break

$ echo $?
1
```

However, as the community user identifies, the app currently silently imports everything up to the "bad" line and drops everything after it.

https://user-images.githubusercontent.com/5934157/192616043-22b34117-063f-4675-a74c-178320bb0950.mp4

Sniffing the traffic to the Zed service confirms the warning is being returned, but it's just not being surfaced in the app.

![image](https://user-images.githubusercontent.com/5934157/192616564-cee0fc99-947a-482e-8ec5-6aa5345f9184.png)

I also confirmed the user's statement that a warning was provided back in GA Brim tagged `v0.26.0` as shown in the attached video.

https://user-images.githubusercontent.com/5934157/192616187-e26c0a51-3a39-4179-a933-487a820b6cd4.mp4

I separately confirmed that the last time the warning was present was in GA Brim tagged `v0.28.0` and then the warning was gone in `v0.29.0`. I attempted to do a binary search between these to find the precise commit where it regressed, but I had difficulty compiling at old commits.

**Comment by philrz** [comment]
Verified in Zui commit a372438.

As shown in the attached video, now the user is shown a warning when this partial load occurs, then they can click this for further detail.

https://user-images.githubusercontent.com/5934157/217348290-efa26495-67bf-4b68-a5be-fc8d00bebe33.mp4

It's been pointed out that the "Load successful" pop-up does represent a contradictory message alongside the "Ingest failed with warnings" message, so #2660 has been opened to improve on that.

Thanks @nwt!
