### ISSUE TITLE
Zed process launched in separate Command Prompt on Windows

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2615]
Repro is at Brim commit e869722.

As shown in the attached video, when starting Brim in dev mode, the `zed.exe` process is now being launched in a separate Command Prompt window. I've also observed this in Zui Insiders, so it seems to affect production builds as well. As far as I can tell it's benign, as I've been able to keep it minimized and otherwise use the app. But I assume this was not intended.

https://user-images.githubusercontent.com/5934157/206558412-2358651e-57f0-4ada-977d-270e30e5aab4.mp4

Via binary search I confirmed that this started happening at commit e869722, which is associated with #2601.

**Comment by nwt** [comment]
@jameskerr: I think it's the Electron bump. See https://github.com/electron/electron/issues/33425.

**Comment by philrz** [comment]
Verified in Zui Insiders [0.30.1-139](https://github.com/brimdata/zui-insiders/releases/tag/v0.30.1-139).

In the attached video, we start out running Zui Insiders v0.30.1-138 and can see the Zed process in its separate Command Prompt window. Once we accept the upgrade to v0.30.1-139 and let it install/restart, the window is no longer visible.

https://user-images.githubusercontent.com/5934157/206869045-6366b689-3be1-4d5a-bf80-d833bbecc4fc.mp4

Thanks @jameskerr!
