### ISSUE TITLE
Refactor viewer component

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#559]
Our viewer can be optimized for faster mounting on the tab pages and [this](https://react-window.now.sh/#/examples/grid/variable-size) library seems like it might facilitate that. Let's refactor the viewer to use that lib.

Additionally, we can connect that new viewer with the up and down arrow shortcuts for selecting logs and ensure that the viewer is always focusing on an area with the selected log in sight when one of those keys has been pressed (i.e. scroll down/up along with the selector).

- [ ] Scroll position
- [ ] Scroll to item 
- [ ] Scroll to index
- [ ] Render a message at the end (end of results)
- [ ] Render an empty message (no results)
- [ ] Sync the selection with the detail pane
- [ ] Show headers / hide headers
- [ ] Have a message if the headers are hidden

In a recent team discussion, @jameskerr noted that this refactor could help us address a set of issues with the Table view, e.g., slowness or problems rendering complex things. I'm linking those issues as being "Blocked" by this one so they're easy to find.

We also acknowledged that we're not sure how long this refactor might take. It could be weeks or it could be days. We'd ideally like to address the related bugs before we release Zui v1.0, so we've committed to spending at least some time in the short term to size up the effort, and if it's too big we'll consider rolling it over to Zui v1.1.

**Comment by philrz** [comment]
The bulk of the ideas described above were addressed in #2626, with the remaining unfinished ones now tracked in #2635.
