### ISSUE TITLE
look for single warning message in search and ingest warning messages

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/brim#621]
Accomodate change in https://github.com/brimsec/zq/pull/591 by ensuring references to warning messages look for a single string, not an array, like:

https://github.com/brimsec/brim/blob/447bf0257abe6e7fdc27f11cda9375c1079e2076/src/js/flows/executeTableSearch.js#L27

**Comment by philrz** [comment]
I don't trust my JavaScript to say this with certainty, but looking at the present state of the code I _think_ we might have addressed this already. @alfred-landrum would you mind having a look, since you'd filed this one?

**Comment by nwt** [comment]
This is no longer relevant.
