### ISSUE TITLE
ZQL with "head" takes 70+ seconds in Brim, but only 13 seconds in zq

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#627]
@mikesbrown originally stumbled onto this one. I've reproduced it here with GA Brim `v0.7.0`.

I start by performing the following query with the `zq` tagged `v0.10.0`, as bundled with the app:

```
# ls -l
total 328912
-rw-r--r--  1 phil  staff  152979527 Apr 16 13:36 all.bzng
-rw-r--r--  1 phil  staff         92 Apr 16 13:32 info.json
-rw-r--r--  1 phil  staff     622381 Apr 16 13:32 packets.idx.json

# time /Applications/Brim.app/Contents/Resources/app/zdeps/zq "head 1000000 | sort id.resp_p" all.bzng
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1428917684.73264;CfkTGq3hZ8De4BPD4h;[fe80::eef4:bbff:fe4f:b245;143;ff02::16;0;]icmp;-;-;-;-;OTH;-;-;0;-;1;76;0;0;-;]
...
real	0m12.497s
user	0m9.185s
sys	0m0.981s
```

Per the attached video, when I do the same in the Brim app, it takes 70+ seconds:

[Query.mp4.zip](https://github.com/brimsec/brim/files/4489814/Query.mp4.zip)

@mikesbrown discussed this one some time back with @jameskerr and learned how if a ZQL program doesn't have `head`, the app appends it to limit the number of records shown in the main panel:

https://github.com/brimsec/brim/blob/952f110a2cd6a9149e02e6d366d7d689642e25d7/src/js/lib/Program.js#L32

However if the user specifies `head` as we did in this case, there's no record limiting, and this apparently causes the bad side effect.

**Comment by mikesbrown** [comment]
A bigger problem is that the Brim app is frozen while processing. If you don't cancel in time, Brim appears stuck. If you are patient and willing to wait, it sorts itself out. But users aren't always going to be that patient.

**Comment by jameskerr** [comment]
One solution to this could be to check the value of the user-supplied "head" to see if it is too big for the app to handle. If so, apply our own "head 500" on top of theirs. Then do the normal the infinite scroll. Is it possible to have `* | head 10000 | head 500` in zql? I would guess so.

**Comment by henridf** [comment]
> Is it possible to have * | head 10000 | head 500 in zql? I would guess so.

It is!

**Comment by jameskerr** [comment]
Great then that will work fine to fix this.

**Comment by jameskerr** [comment]
This is no longer an issue.
