### ISSUE TITLE
windows signing improvements

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/brim#704]
These would be improvements to #549.

I removed the error text that we receive from any createWindowsInstaller failure out of an abundance of caution, because the password to the cert would be printed. I’d like to be able to reintroduce printing that exception should one occur, but it means we have to switch from “standard” createWindowInstaller signing options to use its signWithParams option. I believe this would require importing the certificate using certutil, maybe like this,  in a CI step:
```
certutil -f -user –p password –importpfx brim-signing.pfx
```
and then using some `signtool` params like:
```
signtool.exe sign /a /n "Brim Security" Brim-Setup.exe
```
or maybe the more rigorous
```
signtool.exe sign /sha1 [cert hash] /fd sha256 /td sha256 \
    /tr "http://timestamp.digicert.com/" Brim-Setup.exe
```
These remove the need to send squirrel the password. The `/fd /td /tr` options are orthogonal to password obfuscation but would make our signing look more mature.

**Comment by nwt** [comment]
As of #1508, electron-builder does signing on Windows.
