### ISSUE TITLE
integration test matrix and scheduling rework

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/brim#706]
Here's a straw man for reworking what gets tested on the OS-wise matrix and what isn't, and what moves to a nightly test

- OS-wise testing for ingesting various formats and getting back pcaps, in pre-merge testing.
- OS-wise testing for building release artifacts, in pre-merge testing.
- External APIs tests to be run nightly, **not** in pre-merge testing.
- Everything else to be run on a single OS, in pre-merge testing.

**Comment by jameskerr** [comment]
Closing as a stale issue.
