### ISSUE TITLE
chromedriver startup problems

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/brim#785]
Spectron sometimes can't start chromedriver. The console log failure looks like:
```
    Client initialization failed after 10 attempts: RuntimeError Client initialization failed after 10 attempts: Error: connect ECONNREFUSED 127.0.0.1:9515

      at new RuntimeError (../node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
      at Request._callback (../node_modules/webdriverio/build/lib/utils/RequestHandler.js:342:43)
      at self.callback (../node_modules/request/request.js:185:22)
      at Request.Object.<anonymous>.Request.onRequestError (../node_modules/request/request.js:881:8)
```
This is the Spectron client unable to connect to chromedriver. In saved artifacts, we see chromedriver couldn't start:
```
[1589565717.730][INFO]: Starting ChromeDriver 78.0.3905.1 (c7cce564a78f7c44042856c33e2f3dab0bc4307d-refs/heads/master@{#703739})
[1589565717.730][INFO]: Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1589565717.734][SEVERE]: bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)
[1589565717.734][INFO]: listen on IPv6 failed with error ERR_ADDRESS_IN_USE
```

**Comment by mikesbrown** [comment]
@mattnibs Saw something similar the other day, and [here](https://github.com/brimsec/brim/runs/679031348?check_suite_focus=true) it is again. There are some interesting things going on in this run.

First, let's expand the integration test step to see what test failed. It's:
```
FAIL itest/tests/smoke.test.js (182.723s)
  Smoke test
    √ show the new tab page when you log in (6315ms)
    √ pcap ingest (14290ms)
    × log ingest (161715ms)
```
This corresponds to the following directory in the collected artifacts: `smoke.test.js/3`. The only thing in that directory is the chromedriver.log, pasted in the comment above. The test that ran before would emit the logs directory `smoke.test.js/2`. 

We also see that upload-artifact had failures:
```
File error 'The process cannot access the file 'D:\var\tmp\brimsec\itest\smoke.test.js\2\chromedriver.log' because it is being used by another process.' when uploading file 'D:\var\tmp\brimsec\itest\smoke.test.js\2\chromedriver.log'.
File error 'The process cannot access the file 'D:\var\tmp\brimsec\itest\smoke.test.js\3\Cookies' because it is being used by another process.' when uploading file 'D:\var\tmp\brimsec\itest\smoke.test.js\3\Cookies'.
Associated artifact artifacts-windows-2019-node-12.x (2383666) with run #1179
##[error]The process cannot access the file 'D:\var\tmp\brimsec\itest\smoke.test.js\3\Cookies' because it is being used by another process.
##[error]Exit code 1 returned from process: file name 'c:\runners\2.169.1\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

What stands out here is that `smoke.test.js\2\chromedriver.log` couldn't be saved because a process was using it. And we already know that chromedriver for `smoke.test.js\3` couldn't run because something else was listening on its port.

Next I'm going to look at @mattnibs run from yesterday.

**Comment by mikesbrown** [comment]
[Here's](https://github.com/brimsec/brim/pull/780/checks?check_run_id=675851872) the run. Same symptoms.
1. Windows (btw, `windows_sadness++`)
1. `× log ingest (161729ms)` (same failing test)
1. ```
   File error 'The process cannot access the file 'D:\var\tmp\brimsec\itest\smoke.test.js\2\chromedriver.log' because it is being used by another process.' when uploading file 'D:\var\tmp\brimsec\itest\smoke.test.js\2\chromedriver.log'.
   File error 'The process cannot access the file 'D:\var\tmp\brimsec\itest\smoke.test.js\3\Cookies' because it is being used by another process.' when uploading file 'D:\var\tmp\brimsec\itest\smoke.test.js\3\Cookies'.
   ```
And here's a final interesting piece made clearer in this run:
```
Cleaning up orphan processes
Terminate orphan process: pid (1348) (OpenWith)
Terminate orphan process: pid (664) (cmd)
Terminate orphan process: pid (3644) (node)
Terminate orphan process: pid (820) (electron)
Terminate orphan process: pid (1600) (conhost)
```
I observed orphaned processes in the other run as well, but that run had an additional test failure. In this run, we have only a single test failure.

If we already established smoke3 can't start because smoke2 chromedriver was still running, it's next important to know to which tests these orphaned processes correspond. If they correspond to smoke2, then something isn't happening correctly when the app is closing. If they correspond to smoke3, then chromedriver in smoke2 is slow to close, and spectron is bad about how it handles an app's inability to start.

**Comment by jameskerr** [comment]
Here is another instance of this same bug: https://github.com/brimsec/brim/pull/956/checks?check_run_id=925362786.

**Comment by philrz** [comment]
Since we've moved from Spectron to Playwright for these kinds of tests, I've confirmed with @jameskerr that this issue is no longer relevant and can be closed.
