### ISSUE TITLE
spaces dropdown menu is native, preventing integration testing

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/brim#862]
While Brim was being re-worked to handle pcaps, the integration tests with boom were gutted. At some point before a test that changed spaces was reintroduced, the spaces dropdown menu went native. This means integration tests can't change spaces from the spaces dropdown. A workaround is to open a new tab and click on the space.

**Comment by philrz** [comment]
This dropdown menu is long gone. I've cleared with @jameskerr that it can be closed as no longer relevant.
