### ISSUE TITLE
Infinite scroll in analytics table

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#890]
Right now an analytics table in Brim tops out at 10k entries. This particular repro is on GA Brim tagged `v0.11.0` with the full 70 GB wrccdc Zeek data set:

![image](https://user-images.githubusercontent.com/5934157/85331330-cc0b4a80-b48a-11ea-8464-2b9d4e35a0c1.png)

@jameskerr once made the point:

> "we could do infinite scroll if I had an offset processor"

Admittedly that was over a year ago when things were architecturally a little different, so the specifics may be different now. But suffice to say, at some point we'll likely want to give users a way they can see all their data.

**Comment by jameskerr** [comment]
When the backend creates an offset, we can revisit this.
